/*
ServerEvents.tags('block', event => {
	event.add('kubejs:otherside_ore_replaceables', 'deeperdarker:sculk_stone')
	event.add('kubejs:otherside_ore_replaceables', 'deeperdarker:gloomslate')
	event.add('kubejs:aether_ore_replaceables', 'aether:holystone')
	event.add('kubejs:aether_ore_replaceables', 'aether_redux:divinite')
	event.add('kubejs:aether_ore_replaceables', 'aether_redux:sentrite')
	event.add('minecraft:stone_ore_replaceables', 'minecraft:calcite')
	event.add('minecraft:stone_ore_replaceables', 'minecraft:dripstone_block')
	event.add('minecraft:stone_ore_replaceables', 'create:scoria')
    event.add('minecraft:stone_ore_replaceables', 'create:crimsite')
	event.add('minecraft:stone_ore_replaceables', 'create:limestone')
	event.add('minecraft:stone_ore_replaceables', 'create:veridium')
	event.add('minecraft:stone_ore_replaceables', 'create:asurine')
	event.add('minecraft:stone_ore_replaceables', 'create:ochrum')
	event.add('minecraft:nether_carver_replaceables', 'minecraft:blackstone')
	event.add('minecraft:nether_carver_replaceables', 'create:scoria')
	event.add('minecraft:nether_carver_replaceables', 'create:scorchia')
})
*/
/*
GTCEuServerEvents.fluidVeins(event => {
	event.add('gtceu:helium_3_in_moon', vein => {
        vein.dimensions('ad_astra:moon')
        vein.fluid(() => Fluid.of('gtceu:helium_3').fluid)
        vein.weight(10)
        vein.minimumYield(10)
        vein.maximumYield(40)
        vein.depletionAmount(2)
        vein.depletionChance(1)
        vein.depletedYield(20)
    })
	event.add('gtceu:ice_in_moon', vein => {
        vein.dimensions('ad_astra:moon')
        vein.fluid(() => Fluid.of('gtceu:ice').fluid)
        vein.weight(80)
        vein.minimumYield(60)
        vein.maximumYield(100)
        vein.depletionAmount(2)
        vein.depletionChance(1)
        vein.depletedYield(20)
    })
    event.add('gtceu:water_in_the_aether', vein => {
        vein.addSpawnDimension('aether:the_aether')
        vein.fluid(() => Fluid.of('minecraft:water').fluid)
        vein.weight(600)
        vein.minimumYield(250)
        vein.maximumYield(400)
        vein.depletionAmount(2)
        vein.depletionChance(1)
        vein.depletedYield(50)
    })
    event.add('gtceu:refined_radium_mixture_in_the_aether', vein => {
        vein.addSpawnDimension('aether:the_aether')
        vein.fluid(() => Fluid.of('gtceu:refined_radium_mixture').fluid)
        vein.weight(400)
        vein.minimumYield(80)
        vein.maximumYield(200)
        vein.depletionAmount(2)
        vein.depletionChance(1)
        vein.depletedYield(30)
    })
    event.add('gtceu:lava_in_otherside', vein => {
        vein.addSpawnDimension('deeperdarker:otherside')
        vein.fluid(() => Fluid.of('minecraft:lava').fluid)
        vein.weight(400)
        vein.minimumYield(100)
        vein.maximumYield(220)
        vein.depletionAmount(2)
        vein.depletionChance(1)
        vein.depletedYield(40)
    })
	event.add('gtceu:echo_mixture_in_otherside', vein => {
        vein.addSpawnDimension('deeperdarker:otherside')
        vein.fluid(() => Fluid.of('gtceu:echo_mixture').fluid)
        vein.weight(300)
        vein.minimumYield(20)
        vein.maximumYield(80)
        vein.depletionAmount(2)
        vein.depletionChance(1)
        vein.depletedYield(20)
    })
    event.add('gtceu:shadow_mixture_in_otherside', vein => {
        vein.addSpawnDimension('deeperdarker:otherside')
        vein.fluid(() => Fluid.of('gtceu:shadow_mixture').fluid)
        vein.weight(600)
        vein.minimumYield(50)
        vein.maximumYield(200)
        vein.depletionAmount(2)
        vein.depletionChance(1)
        vein.depletedYield(30)
    })
})
*/

GTCEuServerEvents.oreVeins(event => {
	event.remove("gtceu:naquadah_vein") 
	event.remove("gtceu:scheelite_vein")
	event.remove("gtceu:pitchblende_vein")
	event.remove("gtceu:sheldonite_vein")
	event.remove("gtceu:monazite_vein")
	event.remove("gtnn:molybdenite_vein_tf")
	event.remove("gtnn:lapis_vein_tf")
	event.remove("gtnn:galena_vein_tf")
	event.remove("gtnn:apatite_vein_tf")
	event.remove("gtnn:coal_vein_tf")
	event.remove("gtnn:diamond_vein_tf")
	event.remove("gtnn:lubricant_vein_tf")
	event.remove("gtnn:sapphire_vein_tf")
	event.remove("gtnn:nickel_vein_tf")
	event.remove("gtnn:cassiterite_vein_tf")
	event.remove("gtnn:olivine_vein_tf")
	event.remove("gtnn:salts_vein_tf")
	event.remove("gtnn:iron_vein_tf")
	event.remove("gtnn:gold_vein_tf")
})

ServerEvents.recipes(event => {
  console.log('Ready to modify ore drilling recipes.')

  //remove
  event.remove({ id: 'createoreexcavation:drilling/zinc' })
  event.remove({ id: 'createoreexcavation:drilling/coal' })
  event.remove({ id: 'createoreexcavation:drilling/nether_gold' })
  event.remove({ id: 'createoreexcavation:drilling/redstone' })
  event.remove({ id: 'createoreexcavation:drilling/copper' })
  event.remove({ id: 'createoreexcavation:drilling/iron' })
  event.remove({ id: 'createoreexcavation:drilling/gold' })
  event.remove({ id: 'createoreexcavation:drilling/lapis' })
  event.remove({ id: 'createoreexcavation:drilling/quartz' })
  event.remove({ id: 'createoreexcavation:drilling/emerald' })
  event.remove({ id: 'createoreexcavation:drilling/hardened_diamond' })
  event.remove({ id: 'createoreexcavation:drilling/glowstone' })
  event.remove({ id: 'createoreexcavation:drilling/diamond' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/lapis' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/nether_gold' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/hardened_diamond' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/redstone' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/coal' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/diamond' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/copper' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/zinc' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/iron' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/glowstone' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/quartz' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/gold' })
  event.remove({ id: 'createoreexcavation:ore_vein_type/emerald' })

  //end
  event.recipes.createoreexcavation.vein('{"text": "\u9f99\u606f"}', 'minecraft:dragon_breath').placement(128, 48, 34883410).id("kubejs:dragon_breath")
	.priority(2)
	.veinSize(0.5, 4)
	.biomeWhitelist('minecraft:is_end') 
  event.recipes.createoreexcavation.extracting('create_central_kitchen:dragon_breath 250', 'kubejs:dragon_breath', 640).id("kubejs:dragon_breath_vein")
	.drill('createoreexcavation:netherite_drill')
	.stress(1024)

  event.recipes.createoreexcavation.vein('{"text": "\u672b\u5730\u94dd\u571f\u77ff\u8109"}', 'gtceu:raw_bauxite').placement(64, 16, 38693036).id("kubejs:end_bauxite")
	.priority(4)
	.veinSize(1, 4)
	.biomeWhitelist('minecraft:is_end') 
  event.recipes.createoreexcavation.drilling([Item.of('minecraft:end_stone').withChance(0.66), Item.of('gtceu:raw_bauxite').withChance(0.66), Item.of('gtceu:raw_ilmenite').withChance(0.33), Item.of('gtceu:raw_aluminium').withChance(0.33)], 'kubejs:end_bauxite', 2400).id("kubejs:end_bauxite_vein")
	.fluid('create_central_kitchen:dragon_breath 10')
	.drill('createoreexcavation:netherite_drill')
	.stress(1024)   

  event.recipes.createoreexcavation.vein('{"text": "\u672b\u5730\u78c1\u94c1\u77ff\u8109"}', 'gtceu:raw_magnetite').placement(72, 24, 55277347).id("kubejs:end_magnetite")
	.priority(3)
	.veinSize(0.75, 3)
	.biomeWhitelist('minecraft:is_end') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_magnetite').withChance(0.75), Item.of('gtceu:raw_vanadium_magnetite').withChance(0.5), Item.of('gtceu:raw_chromite').withChance(0.5), Item.of('minecraft:raw_gold').withChance(0.25)], 'kubejs:end_magnetite', 2400).id("kubejs:end_magnetite_vein")
	.fluid('create_central_kitchen:dragon_breath 10')
	.drill('createoreexcavation:netherite_drill')
	.stress(1024)

  event.recipes.createoreexcavation.vein('{"text": "\u672b\u5730\u6ca5\u9752\u94c0\u77ff\u8109"}', 'gtceu:raw_pitchblende').placement(72, 24, 13241255).id("kubejs:end_pitchblende")
	.priority(3)
	.veinSize(0.75, 3)
	.biomeWhitelist('minecraft:is_end') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_pitchblende').withChance(0.75), Item.of('gtceu:raw_uraninite').withChance(0.5)], 'kubejs:end_pitchblende', 2400).id("kubejs:end_pitchblende_vein")
	.fluid('create_central_kitchen:dragon_breath 10')
	.drill('createoreexcavation:netherite_drill')
	.stress(1024)

  //nether
  event.recipes.createoreexcavation.vein('{"text": "\u7194\u5ca9"}', 'minecraft:lava_bucket').placement(64, 8, 34883410).id("kubejs:lava")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.extracting('minecraft:lava 500', 'kubejs:lava', 160).id("kubejs:lava_vein")
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u9edd\u94dc\u77ff\u8109"}', 'gtceu:raw_tetrahedrite').placement(64, 8, 95378524).id("kubejs:nether_tetrahedrite")
	.priority(7)
	.veinSize(3.5, 14)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_tetrahedrite').withChance(0.8), Item.of('minecraft:raw_copper').withChance(0.4), Item.of('gtceu:raw_stibnite').withChance(0.2)], 'kubejs:nether_tetrahedrite', 1200).id("kubejs:nether_tetrahedrite_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u7ea2\u77f3\u77ff\u8109"}', 'gtceu:raw_redstone').placement(64, 16, 62388984).id("kubejs:nether_redstone")
	.priority(6)
	.veinSize(3, 12)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_redstone').withChance(0.75), Item.of('gtceu:raw_ruby').withChance(0.5), Item.of('gtceu:raw_cinnabar').withChance(0.25)], 'kubejs:nether_redstone', 1200).id("kubejs:nether_redstone_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u785d\u77f3\u77ff\u8109"}', 'gtceu:raw_saltpeter').placement(96, 24, 34612145).id("kubejs:nether_saltpeter")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('minecraft:netherrack').withChance(0.5), Item.of('gtceu:raw_saltpeter').withChance(0.75), Item.of('gtceu:raw_diatomite').withChance(0.5), Item.of('gtceu:raw_electrotine').withChance(0.5), Item.of('gtceu:raw_alunite').withChance(0.25)], 'kubejs:nether_saltpeter', 1200).id("kubejs:nether_saltpeter_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u94cd\u77ff\u8109"}', 'gtceu:raw_beryllium').placement(128, 32, 85733525).id("kubejs:nether_beryllium")
	.priority(3)
	.veinSize(1.5, 6)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_beryllium').withChance(0.75), Item.of('gtceu:raw_emerald').withChance(0.5), Item.of('gtceu:raw_emerald').withChance(0.5)], 'kubejs:nether_beryllium', 1200).id("kubejs:nether_beryllium_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u9530\u77ff\u8109"}', 'gtceu:raw_pyrolusite').placement(128, 64, 64773246).id("kubejs:nether_pyrolusite")
	.priority(2)
	.veinSize(1, 4)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_grossular').withChance(0.75), Item.of('gtceu:raw_pyrolusite').withChance(0.5), Item.of('gtceu:raw_tantalite').withChance(0.25)], 'kubejs:nether_pyrolusite', 1200).id("kubejs:nether_pyrolusite_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u94bc\u77ff\u8109"}', 'gtceu:raw_molybdenum').placement(64, 24, 16733536).id("kubejs:nether_molybdenum")
	.priority(5)
	.veinSize(2.5, 10)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_wulfenite').withChance(0.75), Item.of('gtceu:raw_molybdenite').withChance(0.5), Item.of('gtceu:raw_molybdenum').withChance(0.25), Item.of('gtceu:raw_powellite').withChance(0.25)], 'kubejs:nether_molybdenum', 1200).id("kubejs:nether_molybdenum_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u5e26\u72b6\u94c1\u77ff\u8109"}', 'gtceu:raw_goethite').placement(128, 64, 62412224).id("kubejs:nether_goethite")
	.priority(3)
	.veinSize(1.5, 6)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_goethite').withChance(0.75), Item.of('gtceu:raw_yellow_limonite').withChance(0.5), Item.of('gtceu:raw_hematite').withChance(0.5), Item.of('minecraft:raw_gold').withChance(0.25)], 'kubejs:nether_goethite', 1200).id("kubejs:nether_goethite_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u8d5b\u7279\u65af\u77f3\u82f1"}', 'gtceu:raw_certus_quartz').placement(128, 32, 74535121).id("kubejs:nether_certus_quartz")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_quartzite').withChance(0.75), Item.of('gtceu:raw_certus_quartz').withChance(0.5), Item.of('gtceu:raw_barite').withChance(0.25)], 'kubejs:nether_certus_quartz', 1200).id("kubejs:nether_certus_quartz_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)
																																																																																																									
  event.recipes.createoreexcavation.vein('{"text": "\u9ec4\u7389\u77ff\u8109"}', 'gtceu:raw_topaz').placement(64, 16, 73422223).id("kubejs:nether_topaz")
	.priority(7)
	.veinSize(3.5, 14)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_blue_topaz').withChance(0.75), Item.of('gtceu:raw_topaz').withChance(0.5), Item.of('gtceu:raw_chalcocite').withChance(0.25), Item.of('gtceu:raw_bornite').withChance(0.25)], 'kubejs:nether_topaz', 1200).id("kubejs:nether_topaz_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)
 
  event.recipes.createoreexcavation.vein('{"text": "\u4e0b\u754c\u77f3\u82f1\u77ff\u8109"}', 'gtceu:raw_nether_quartz').placement(64, 8, 56266722).id("kubejs:nether_quartz")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('minecraft:netherrack').withChance(0.5), Item.of('gtceu:raw_nether_quartz').withChance(0.75), Item.of('gtceu:raw_quartzite').withChance(0.25)], 'kubejs:nether_quartz', 1200).id("kubejs:nether_quartz_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  event.recipes.createoreexcavation.vein('{"text": "\u786b\u77ff\u8109"}', 'gtceu:raw_sulfur').placement(32, 8, 72552141).id("kubejs:nether_sulfur")
	.priority(10)
	.veinSize(5, 20)
	.biomeWhitelist('minecraft:is_nether') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_sulfur').withChance(0.75), Item.of('gtceu:raw_pyrite').withChance(0.5), Item.of('gtceu:raw_sphalerite').withChance(0.25)], 'kubejs:nether_sulfur', 1200).id("kubejs:nether_sulfur_vein")
	.fluid('minecraft:lava 10')
	.drill('createoreexcavation:diamond_drill')
	.stress(512)

  //overworld
  event.recipes.createoreexcavation.vein('{"text": "\u78f7\u7070\u77f3\u77ff\u8109"}', 'gtceu:raw_apatite').placement(96, 24, 61787233).id("kubejs:apatite")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_apatite').withChance(0.75), Item.of('gtceu:raw_tricalcium_phosphate').withChance(0.5), Item.of('gtceu:raw_pyrochlore').withChance(0.25)], 'kubejs:apatite', 600).id("kubejs:apatite_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u9521\u77f3\u77ff\u8109"}', 'gtceu:raw_tin').placement(64, 16, 95124462).id("kubejs:tin")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_tin').withChance(0.8), Item.of('gtceu:raw_cassiterite').withChance(0.4)], 'kubejs:tin', 600).id("kubejs:tin_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u7164\u70ad\u77ff\u8109"}', 'gtceu:raw_coal').placement(64, 16, 72435621).id("kubejs:coal")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_coal').withChance(0.75)], 'kubejs:coal', 600).id("kubejs:coal_vein")
	.stress(256)
  
  event.recipes.createoreexcavation.vein('{"text": "\u94dc\u9521\u77ff\u8109"}', 'gtceu:raw_chalcopyrite').placement(96, 24, 96322467).id("kubejs:chalcopyrite")
	.priority(5)
	.veinSize(2.5, 10)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_chalcopyrite').withChance(0.9), Item.of('gtceu:raw_zeolite').withChance(0.36), Item.of('gtceu:raw_cassiterite').withChance(0.36), Item.of('gtceu:raw_realgar').withChance(0.18)], 'kubejs:chalcopyrite', 600).id("kubejs:chalcopyrite_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u65b9\u94c5\u77ff\u8109"}', 'gtceu:raw_galena').placement(96, 32, 15668754).id("kubejs:galena")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_galena').withChance(0.75), Item.of('gtceu:raw_silver').withChance(0.5), Item.of('gtceu:raw_lead').withChance(0.25)], 'kubejs:galena', 600).id("kubejs:galena_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u9521\u77f3\u69b4\u77f3\u77ff\u8109"}', 'gtceu:raw_cassiterite_sand').placement(64, 16, 73424672).id("kubejs:cassiterite")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('minecraft:sand').withChance(0.5), Item.of('gtceu:raw_cassiterite_sand').withChance(0.75), Item.of('gtceu:raw_garnet_sand').withChance(0.5), Item.of('gtceu:raw_asbestos').withChance(0.5), Item.of('gtceu:raw_diatomite').withChance(0.25)], 'kubejs:cassiterite', 600).id("kubejs:cassiterite_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u77f3\u69b4\u77f3\u77ff\u8109"}', 'gtceu:raw_red_garnet').placement(96, 32, 98652543).id("kubejs:garnet")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_red_garnet').withChance(0.75), Item.of('gtceu:raw_yellow_garnet').withChance(0.5), Item.of('gtceu:raw_amethyst').withChance(0.5), Item.of('gtceu:raw_opal').withChance(0.25)], 'kubejs:garnet', 600).id("kubejs:garnet_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u94c1\u77ff\u8109"}', 'gtceu:raw_goethite').placement(32, 4, 64356633).id("kubejs:goethite")
	.priority(12)
	.veinSize(6, 24)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_goethite').withChance(0.9), Item.of('gtceu:raw_yellow_limonite').withChance(0.36), Item.of('gtceu:raw_hematite').withChance(0.36), Item.of('gtceu:raw_malachite').withChance(0.18)], 'kubejs:goethite', 600).id("kubejs:goethite_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u7682\u6ed1\u77ff\u8109"}', 'gtceu:raw_soapstone').placement(96, 32, 64356633).id("kubejs:soapstone")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_soapstone').withChance(0.75), Item.of('gtceu:raw_talc').withChance(0.5), Item.of('gtceu:raw_glauconite_sand').withChance(0.5), Item.of('gtceu:raw_pentlandite').withChance(0.25)], 'kubejs:soapstone', 600).id("kubejs:soapstone_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u4e3b\u4e16\u754c\u78c1\u94c1\u77ff\u8109"}', 'gtceu:raw_magnetite').placement(64, 16, 62467543).id("kubejs:magnetite")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_magnetite').withChance(0.75), Item.of('gtceu:raw_vanadium_magnetite').withChance(0.5), Item.of('minecraft:raw_gold').withChance(0.25)], 'kubejs:magnetite', 600).id("kubejs:magnetite_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u77ff\u7802\u77ff\u8109"}', 'gtceu:raw_basaltic_mineral_sand').placement(64, 16, 23456161).id("kubejs:mineral_sand")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('minecraft:sand').withChance(0.5), Item.of('gtceu:raw_basaltic_mineral_sand').withChance(0.75), Item.of('gtceu:raw_granitic_mineral_sand').withChance(0.5), Item.of('gtceu:raw_fullers_earth').withChance(0.5), Item.of('gtceu:raw_gypsum').withChance(0.25)], 'kubejs:mineral_sand', 600).id("kubejs:mineral_sand_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u954d\u77ff\u8109"}', 'gtceu:raw_nickel').placement(96, 32, 56151456).id("kubejs:nickel")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_garnierite').withChance(0.75), Item.of('gtceu:raw_nickel').withChance(0.5), Item.of('gtceu:raw_cobaltite').withChance(0.5), Item.of('gtceu:raw_pentlandite').withChance(0.25)], 'kubejs:nickel', 600).id("kubejs:nickel_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u76d0\u77ff\u8109"}', 'gtceu:raw_salt').placement(96, 24, 66436533).id("kubejs:salt")
	.priority(5)
	.veinSize(2.5, 10)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_rock_salt').withChance(0.75), Item.of('gtceu:raw_salt').withChance(0.5), Item.of('gtceu:raw_lepidolite').withChance(0.25), Item.of('gtceu:raw_spodumene').withChance(0.25)], 'kubejs:salt', 600).id("kubejs:salt_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u76d0\u77ff\u8109"}', 'gtceu:raw_oilsands').placement(96, 32, 35551613).id("kubejs:oilsands")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_oilsands').withChance(0.75), Item.of('gtceu:raw_oilsands').withChance(0.5), Item.of('gtceu:raw_oilsands').withChance(0.25)], 'kubejs:oilsands', 600).id("kubejs:oilsands_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u94dc\u77ff\u8109"}', 'minecraft:raw_copper').placement(64, 16, 97543355).id("kubejs:copper")
	.priority(8)
	.veinSize(4, 16)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_chalcopyrite').withChance(0.9), Item.of('minecraft:raw_iron').withChance(0.36), Item.of('gtceu:raw_pyrite').withChance(0.36), Item.of('minecraft:raw_copper').withChance(0.36)], 'kubejs:copper', 600).id("kubejs:copper_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u94bb\u77f3\u77ff\u8109"}', 'gtceu:raw_diamond').placement(96, 32, 34579969).id("kubejs:diamond")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_graphite').withChance(0.75), Item.of('gtceu:raw_diamond').withChance(0.5), Item.of('gtceu:raw_coal').withChance(0.25)], 'kubejs:diamond', 600).id("kubejs:diamond_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u9752\u91d1\u77f3\u77ff\u8109"}', 'gtceu:raw_lapis').placement(96, 32, 67490744).id("kubejs:lapis")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_lazurite').withChance(0.75), Item.of('gtceu:raw_sodalite').withChance(0.5), Item.of('gtceu:raw_lapis').withChance(0.5), Item.of('gtceu:raw_calcite').withChance(0.25)], 'kubejs:lapis', 600).id("kubejs:lapis_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u4e3b\u4e16\u754c\u9530\u77ff\u8109"}', 'gtceu:raw_pyrolusite').placement(96, 32, 34400053).id("kubejs:grossular")
	.priority(4)
	.veinSize(2, 8)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_grossular').withChance(0.75), Item.of('gtceu:raw_spessartine').withChance(0.5), Item.of('gtceu:raw_pyrolusite').withChance(0.5), Item.of('gtceu:raw_tantalite').withChance(0.25)], 'kubejs:grossular', 600).id("kubejs:grossular_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u4e91\u6bcd\u77ff\u8109"}', 'gtceu:raw_mica').placement(128, 64, 24793600).id("kubejs:mica")
	.priority(2)
	.veinSize(1, 4)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_kyanite').withChance(0.75), Item.of('gtceu:raw_mica').withChance(0.5), Item.of('gtceu:raw_bauxite').withChance(0.5), Item.of('gtceu:raw_pollucite').withChance(0.25)], 'kubejs:mica', 600).id("kubejs:mica_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u6a44\u6984\u77f3\u77ff\u8109"}', 'gtceu:raw_olivine').placement(128, 64, 91949692).id("kubejs:olivine")
	.priority(2)
	.veinSize(1, 4)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_bentonite').withChance(0.75), Item.of('gtceu:raw_magnetite').withChance(0.5), Item.of('gtceu:raw_olivine').withChance(0.5), Item.of('gtceu:raw_glauconite_sand').withChance(0.25)], 'kubejs:olivine', 600).id("kubejs:olivine_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u4e3b\u4e16\u754c\u7ea2\u77f3\u77ff\u8109"}', 'gtceu:raw_redstone').placement(80, 24, 58423675).id("kubejs:redstone")
	.priority(6)
	.veinSize(3, 12)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_redstone').withChance(0.75), Item.of('gtceu:raw_ruby').withChance(0.5), Item.of('gtceu:raw_cinnabar').withChance(0.25)], 'kubejs:redstone', 600).id("kubejs:redstone_vein")
	.stress(256)

  event.recipes.createoreexcavation.vein('{"text": "\u84dd\u5b9d\u77f3\u77ff\u8109"}', 'gtceu:raw_sapphire').placement(80, 24, 73355842).id("kubejs:sapphire")
	.priority(6)
	.veinSize(3, 12)
	.biomeWhitelist('minecraft:is_overworld') 
  event.recipes.createoreexcavation.drilling([Item.of('gtceu:raw_almandine').withChance(0.75), Item.of('gtceu:raw_pyrope').withChance(0.5), Item.of('gtceu:raw_sapphire').withChance(0.25), Item.of('gtceu:raw_green_sapphire').withChance(0.25)], 'kubejs:sapphire', 600).id("kubejs:sapphire_vein")
	.stress(256)

  //gtceu
  /*
  event.recipes.gtceu.assembler('bedrock_miner_mv')
      .itemInputs('gtceu:mv_machine_hull', '4x gtceu:steel_frame', '4x #gtceu:circuits/mv', '4x gtceu:mv_electric_motor', '4x gtceu:mv_electric_pump', '4x gtceu:mv_conveyor_module', '4x gtceu:vanadium_steel_gear', 'gtceu:diamond_drill_head')
      .itemOutputs('gtceu:mv_bedrock_ore_miner')
      .duration(400)
      .EUt(120)
      .circuit(3)
  event.recipes.gtceu.assembler('bedrock_miner_hv')
      .itemInputs('gtceu:ev_machine_hull', '4x gtceu:titanium_frame', '4x #gtceu:circuits/ev', '4x gtceu:ev_electric_motor', '4x gtceu:ev_electric_pump', '4x gtceu:ev_conveyor_module', '4x gtceu:tungsten_carbide_gear', 'gtceu:tungsten_carbide_drill_head')
      .itemOutputs('gtceu:hv_bedrock_ore_miner')
      .duration(400)
      .EUt(1920)
      .circuit(3)
  event.recipes.gtceu.assembler('bedrock_miner_ev')
      .itemInputs('gtceu:luv_machine_hull', '4x gtceu:tungsten_steel_frame', '4x #gtceu:circuits/luv', '4x gtceu:luv_electric_motor', '4x gtceu:luv_electric_pump', '4x gtceu:luv_conveyor_module', '4x gtceu:osmiridium_gear', 'gtceu:hsse_drill_head')
      .itemOutputs('gtceu:ev_bedrock_ore_miner')
      .duration(400)
      .EUt(30720)
      .circuit(3)
  */
})