ServerEvents.tags('item', event => {
  event.add('minecraft:music_discs', 'kubejs:disc_key')
  event.add('minecraft:music_discs', 'kubejs:disc_door')
  event.add('minecraft:music_discs', 'kubejs:disc_subwoofer_lullaby')
  event.add('minecraft:music_discs', 'kubejs:disc_living_mice')
  event.add('minecraft:music_discs', 'kubejs:disc_moog_city')
  event.add('minecraft:music_discs', 'kubejs:disc_haggstrom')
  event.add('minecraft:music_discs', 'kubejs:disc_minecraft')
  event.add('minecraft:music_discs', 'kubejs:disc_oxygene')
  event.add('minecraft:music_discs', 'kubejs:disc_equinoxe')
  event.add('minecraft:music_discs', 'kubejs:disc_mice_on_venus')
  event.add('minecraft:music_discs', 'kubejs:disc_dry_hands')
  event.add('minecraft:music_discs', 'kubejs:disc_wet_hands')
  event.add('minecraft:music_discs', 'kubejs:disc_clark')
  event.add('minecraft:music_discs', 'kubejs:disc_chris')
  event.add('minecraft:music_discs', 'kubejs:disc_excuse')
  event.add('minecraft:music_discs', 'kubejs:disc_sweden')
  event.add('minecraft:music_discs', 'kubejs:disc_dog')
  event.add('minecraft:music_discs', 'kubejs:disc_danny')
  event.add('minecraft:music_discs', 'kubejs:disc_beginning')
  event.add('minecraft:music_discs', 'kubejs:disc_droopy_likes_ricochet')
  event.add('minecraft:music_discs', 'kubejs:disc_droopy_likes_your_face')

  event.add('minecraft:music_discs', 'kubejs:disc_ki')
  event.add('minecraft:music_discs', 'kubejs:disc_alpha')
  event.add('minecraft:music_discs', 'kubejs:disc_dead_voxel')
  event.add('minecraft:music_discs', 'kubejs:disc_blind_spots')
  event.add('minecraft:music_discs', 'kubejs:disc_flake')
  event.add('minecraft:music_discs', 'kubejs:disc_moog_city_2')
  event.add('minecraft:music_discs', 'kubejs:disc_concrete_halls')
  event.add('minecraft:music_discs', 'kubejs:disc_biome_fest')
  event.add('minecraft:music_discs', 'kubejs:disc_mutation')
  event.add('minecraft:music_discs', 'kubejs:disc_haunt_muskie')
  event.add('minecraft:music_discs', 'kubejs:disc_warmth')
  event.add('minecraft:music_discs', 'kubejs:disc_floating_trees')
  event.add('minecraft:music_discs', 'kubejs:disc_aria_math')
  event.add('minecraft:music_discs', 'kubejs:disc_kyoto')
  event.add('minecraft:music_discs', 'kubejs:disc_ballad_of_the_cats')
  event.add('minecraft:music_discs', 'kubejs:disc_taswell')
  event.add('minecraft:music_discs', 'kubejs:disc_beginning_2')
  event.add('minecraft:music_discs', 'kubejs:disc_dreiton')
  event.add('minecraft:music_discs', 'kubejs:disc_the_end')

  event.add('minecraft:music_discs', 'kubejs:disc_axolotl')
  event.add('minecraft:music_discs', 'kubejs:disc_dragon_fish')
  event.add('minecraft:music_discs', 'kubejs:disc_shuniji')

  event.add('minecraft:music_discs', 'kubejs:disc_chrysopoeia')
  event.add('minecraft:music_discs', 'kubejs:disc_rubedo')
  event.add('minecraft:music_discs', 'kubejs:disc_so_below')

  event.add('minecraft:music_discs', 'kubejs:disc_an_ordinary_day')
  event.add('minecraft:music_discs', 'kubejs:disc_comforting_memories')
  event.add('minecraft:music_discs', 'kubejs:disc_floating_dream')
  event.add('minecraft:music_discs', 'kubejs:disc_ancestry')
  event.add('minecraft:music_discs', 'kubejs:disc_infinite_amethyst')
  event.add('minecraft:music_discs', 'kubejs:disc_left_to_bloom')
  event.add('minecraft:music_discs', 'kubejs:disc_one_more_day')
  event.add('minecraft:music_discs', 'kubejs:disc_stand_tall')
  event.add('minecraft:music_discs', 'kubejs:disc_wending')

  event.add('minecraft:music_discs', 'kubejs:disc_labyrinthine')
  event.add('minecraft:music_discs', 'kubejs:disc_aerie')
  event.add('minecraft:music_discs', 'kubejs:disc_firebugs')

  event.add('minecraft:music_discs', 'kubejs:disc_echo_in_the_wind')
  event.add('minecraft:music_discs', 'kubejs:disc_a_familiar_room')
  event.add('minecraft:music_discs', 'kubejs:disc_bromeliad')
  event.add('minecraft:music_discs', 'kubejs:disc_crescent_dunes')

  event.add('minecraft:music_discs', 'kubejs:disc_creator')
  event.add('minecraft:music_discs', 'kubejs:disc_creator_music_box')
  event.add('minecraft:music_discs', 'kubejs:disc_deeper')
  event.add('minecraft:music_discs', 'kubejs:disc_eld_unknown')
  event.add('minecraft:music_discs', 'kubejs:disc_endless')
  event.add('minecraft:music_discs', 'kubejs:disc_featherfall')
  event.add('minecraft:music_discs', 'kubejs:disc_komorebi')
  event.add('minecraft:music_discs', 'kubejs:disc_pokopoko')
  event.add('minecraft:music_discs', 'kubejs:disc_precipice')
  event.add('minecraft:music_discs', 'kubejs:disc_puzzlebox')
  event.add('minecraft:music_discs', 'kubejs:disc_watcher')
  event.add('minecraft:music_discs', 'kubejs:disc_yakusoku')

  event.add('forge:dusts/obsidian', 'create:powdered_obsidian')
  event.add('forge:ingots/andesite_alloy', 'create:andesite_alloy')
  event.add('forge:plates/andesite_alloy', 'createdeco:andesite_sheet')
  event.add('forge:ingots/refined_radiance', 'createchromaticreturn:refined_radiance')
  event.add('forge:ingots/shadow_steel', 'createchromaticreturn:shadow_steel')
  event.add('forge:dusts/shadow_steel', 'createchromaticreturn:shadow_steel_powder')
  event.add('forge:dusts/ender_pearl', 'enderio:powdered_ender_pearl')
  event.add('forge:ingots/multiplite', 'createchromaticreturn:multiplite_ingot')
  event.add('forge:ingots/durasteel', 'createchromaticreturn:durasteel_ingot')
  event.add('forge:nuggets/netherite', 'createdeco:netherite_nugget')
  event.add('forge:plates/netherite', 'createdeco:netherite_sheet')
  event.add('forge:plates/zinc', 'createdeco:zinc_sheet')
  event.add('forge:plates/andesite_alloy', 'vintageimprovements:andesite_sheet')

  event.add('forge:springs/blaze', 'vintageimprovements:blaze_spring')
  event.add('forge:springs/brass', 'vintageimprovements:brass_spring')
  event.add('forge:springs/copper', 'vintageimprovements:copper_spring')
  event.add('forge:springs/electrum', 'vintageimprovements:electrum_spring')
  event.add('forge:springs/gold', 'vintageimprovements:golden_spring')
  event.add('forge:springs/iron', 'vintageimprovements:iron_spring')
  event.add('forge:springs/steel', 'vintageimprovements:steel_spring')
  event.add('forge:springs/netherite', 'vintageimprovements:netherite_spring')
  event.add('forge:springs/andesite', 'vintageimprovements:andesite_spring')
  event.add('forge:springs/bronze', 'vintageimprovements:bronze_spring')
  event.add('forge:springs/cast_iron', 'vintageimprovements:cast_iron_spring')
  event.add('forge:springs/cobalt', 'vintageimprovements:cobalt_spring')
  event.add('forge:springs/osmium', 'vintageimprovements:osmium_spring')
  event.add('forge:springs/invar', 'vintageimprovements:invar_spring')
  event.add('forge:springs/lead', 'vintageimprovements:lead_spring')
  event.add('forge:springs/nethersteel', 'vintageimprovements:nethersteel_spring')
  event.add('forge:springs/nickel', 'vintageimprovements:nickel_spring')
  event.add('forge:springs/palladium', 'vintageimprovements:palladium_spring')
  event.add('forge:springs/platinum', 'vintageimprovements:platinum_spring')
  event.add('forge:springs/rhodium', 'vintageimprovements:rhodium_spring')
  event.add('forge:springs/rose_gold', 'vintageimprovements:rose_gold_spring')
  event.add('forge:springs/silver', 'vintageimprovements:silver_spring')
  event.add('forge:springs/tin', 'vintageimprovements:tin_spring')
  event.add('forge:springs/uranium', 'vintageimprovements:uranium_spring')
  event.add('forge:springs/vanadium', 'vintageimprovements:vanadium_spring')
  event.add('forge:springs/zinc', 'vintageimprovements:zinc_spring')

  event.add('forge:small_springs/brass', 'vintageimprovements:small_brass_spring')
  event.add('forge:small_springs/copper', 'vintageimprovements:small_copper_spring')
  event.add('forge:small_springs/electrum', 'vintageimprovements:small_electrum_spring')
  event.add('forge:small_springs/gold', 'vintageimprovements:small_golden_spring')
  event.add('forge:small_springs/iron', 'vintageimprovements:small_iron_spring')
  event.add('forge:small_springs/steel', 'vintageimprovements:small_steel_spring')
  event.add('forge:small_springs/andesite', 'vintageimprovements:small_andesite_spring')
  event.add('forge:small_springs/bronze', 'vintageimprovements:small_bronze_spring')
  event.add('forge:small_springs/cast_iron', 'vintageimprovements:small_cast_iron_spring')
  event.add('forge:small_springs/cobalt', 'vintageimprovements:small_cobalt_spring')
  event.add('forge:small_springs/osmium', 'vintageimprovements:small_osmium_spring')
  event.add('forge:small_springs/invar', 'vintageimprovements:small_invar_spring')
  event.add('forge:small_springs/nickel', 'vintageimprovements:small_nickel_spring')
  event.add('forge:small_springs/palladium', 'vintageimprovements:small_palladium_spring')
  event.add('forge:small_springs/platinum', 'vintageimprovements:small_platinum_spring')
  event.add('forge:small_springs/rhodium', 'vintageimprovements:small_rhodium_spring')
  event.add('forge:small_springs/rose_gold', 'vintageimprovements:small_rose_gold_spring')
  event.add('forge:small_springs/silver', 'vintageimprovements:small_silver_spring')
  event.add('forge:small_springs/tin', 'vintageimprovements:small_tin_spring')
  event.add('forge:small_springs/uranium', 'vintageimprovements:small_uranium_spring')
  event.add('forge:small_springs/vanadium', 'vintageimprovements:small_vanadium_spring')
  event.add('forge:small_springs/zinc', 'vintageimprovements:small_zinc_spring')

  event.add("gtceu:circuits/ulv", ["kubejs:ulv_cosmic_brain", "create_connected:control_chip"])
  event.add("gtceu:circuits/lv", ["kubejs:lv_cosmic_brain", "kubejs:electronic_mechanism"])
  event.add("gtceu:circuits/mv", "kubejs:mv_cosmic_brain")
  event.add("gtceu:circuits/hv", "kubejs:hv_cosmic_brain")
  event.add("gtceu:circuits/ev", "kubejs:ev_cosmic_brain")
  event.add("gtceu:circuits/iv", "kubejs:iv_cosmic_brain")
  event.add("gtceu:circuits/luv", "kubejs:luv_cosmic_brain")
  event.add("gtceu:circuits/zpm", ["kubejs:zpm_cosmic_brain", "kubejs:echo_processor"])
  event.add("gtceu:circuits/uv", ["kubejs:uv_cosmic_brain", "kubejs:quark_processor", "kubejs:echo_assembly"])
  event.add("gtceu:circuits/uhv", ["kubejs:uhv_cosmic_brain", "kubejs:timewarp_processor", "kubejs:quark_assembly", "kubejs:echo_computer"])
  event.add("gtceu:circuits/uev", ["kubejs:uev_cosmic_brain", "kubejs:blackhole_processor", "kubejs:timewarp_assembly", "kubejs:quark_computer", "kubejs:echo_mainframe"])
  event.add("gtceu:circuits/uiv", ["kubejs:uiv_cosmic_brain", "kubejs:blackhole_assembly", "kubejs:timewarp_computer", "kubejs:quark_mainframe"])
  event.add("gtceu:circuits/uxv", ["kubejs:uxv_cosmic_brain", "kubejs:blackhole_computer", "kubejs:timewarp_mainframe"])
  event.add("gtceu:circuits/opv", ["kubejs:opv_cosmic_brain", "kubejs:blackhole_mainframe"])
  event.add("gtceu:circuits/max", "kubejs:max_cosmic_brain")

  event.remove("quark:stone_tool_materials", "minecraft:flint")
})

ServerEvents.tags('entity_type', event => {
  event.add('ad_astra:can_survive_in_space', 'cataclysm:ignis')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:ignited_revenant')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:ignited_berserker')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:kobolediator')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:koboleton')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:wadjet')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:modern_remnant')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:ancient_remnant')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:the_harbinger')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:the_prowler')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:the_watcher')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:wither_storm')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:wither_storm_segment')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:wither_storm_head')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:withered_symbiont')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_chicken')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_cow')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_creeper')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_iron_golem')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_mushroom_cow')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_phantom')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_pillager')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_skeleton')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_spider')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_villager')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:sickened_zombie')
  event.add('ad_astra:can_survive_in_space', 'cataclysm:command_block')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:mutant_creeper')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:mutant_enderman')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:endersoul_fragment')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:endersoul_clone')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:mutant_skeleton')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:mutant_snow_golem')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:mutant_zombie')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:spider_pig')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:creeper_minion_egg')
  event.add('ad_astra:can_survive_in_space', 'mutantmonsters:creeper_minion')

  event.add('ars_nouveau:jar_blacklist', 'cataclysm:ignis')
  event.add('ars_nouveau:drygmy_blacklist', 'cataclysm:ignis')
  event.add('ars_nouveau:jar_blacklist', 'cataclysm:ancient_remnant')
  event.add('ars_nouveau:drygmy_blacklist', 'cataclysm:ancient_remnant')
  event.add('ars_nouveau:jar_blacklist', 'cataclysm:the_harbinger')
  event.add('ars_nouveau:drygmy_blacklist', 'cataclysm:the_harbinger')
  event.add('ars_nouveau:jar_blacklist', 'cataclysm:ender_guardian')
  event.add('ars_nouveau:drygmy_blacklist', 'cataclysm:ender_guardian')
  event.add('ars_nouveau:jar_blacklist', 'cataclysm:netherite_monstrosity')
  event.add('ars_nouveau:drygmy_blacklist', 'cataclysm:netherite_monstrosity')
  event.add('ars_nouveau:jar_blacklist', 'cataclysm:the_leviathan')
  event.add('ars_nouveau:drygmy_blacklist', 'cataclysm:the_leviathan')
  event.add('ars_nouveau:jar_blacklist', 'minecraft:ender_dragon')
  event.add('ars_nouveau:drygmy_blacklist', 'minecraft:ender_dragon')
  event.add('ars_nouveau:jar_blacklist', 'minecraft:wither')
  event.add('ars_nouveau:drygmy_blacklist', 'minecraft:wither')
  event.add('ars_nouveau:jar_blacklist', 'ars_nouveau:wilden_boss')
  event.add('ars_nouveau:drygmy_blacklist', 'ars_nouveau:wilden_boss')
  event.add('ars_nouveau:jar_blacklist', 'bosses_of_mass_destruction:gauntlet')
  event.add('ars_nouveau:drygmy_blacklist', 'bosses_of_mass_destruction:gauntlet')
  event.add('ars_nouveau:jar_blacklist', 'bosses_of_mass_destruction:lich')
  event.add('ars_nouveau:drygmy_blacklist', 'bosses_of_mass_destruction:lich')
  event.add('ars_nouveau:jar_blacklist', 'bosses_of_mass_destruction:obsidilith')
  event.add('ars_nouveau:drygmy_blacklist', 'bosses_of_mass_destruction:obsidilith')
  event.add('ars_nouveau:jar_blacklist', 'bosses_of_mass_destruction:void_blossom')
  event.add('ars_nouveau:drygmy_blacklist', 'bosses_of_mass_destruction:void_blossom')
  event.add('ars_nouveau:jar_blacklist', 'witherstormmod:wither_storm')
  event.add('ars_nouveau:drygmy_blacklist', 'witherstormmod:withered_symbiont')
})