/*
GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    event.create('sculk_stone', 'ore')
        .stateSupplier(() => Block.getBlock('deeperdarker:sculk_stone').defaultBlockState())
        .baseModelLocation('deeperdarker:block/sculk_stone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('gloomslate', 'ore')
        .stateSupplier(() => Block.getBlock('deeperdarker:gloomslate').defaultBlockState())
        .baseModelLocation('deeperdarker:block/gloomslate')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('holystone', 'ore')
        .stateSupplier(() => Block.getBlock('aether:holystone').defaultBlockState())
        .baseModelLocation('aether:block/holystone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('divinite', 'ore')
        .stateSupplier(() => Block.getBlock('aether_redux:divinite').defaultBlockState())
        .baseModelLocation('aether_redux:block/divinite')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('sentrite', 'ore')
        .stateSupplier(() => Block.getBlock('aether_redux:sentrite').defaultBlockState())
        .baseModelLocation('aether_redux:block/sentrite')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('dripstone', 'ore')
        .stateSupplier(() => Block.getBlock('minecraft:dripstone_block').defaultBlockState())
        .baseModelLocation('minecraft:block/dripstone_block')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('calcite', 'ore')
        .stateSupplier(() => Block.getBlock('minecraft:calcite').defaultBlockState())
        .baseModelLocation('minecraft:block/calcite')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('crimsite', 'ore')
        .stateSupplier(() => Block.getBlock('create:crimsite').defaultBlockState())
        .baseModelLocation('create:block/crimsite_natural_0')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('limestone', 'ore')
        .stateSupplier(() => Block.getBlock('create:limestone').defaultBlockState())
        .baseModelLocation('create:block/limestone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('veridium', 'ore')
        .stateSupplier(() => Block.getBlock('create:veridium').defaultBlockState())
        .baseModelLocation('create:block/veridium_natural_0')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('asurine', 'ore')
        .stateSupplier(() => Block.getBlock('create:asurine').defaultBlockState())
        .baseModelLocation('create:block/asurine_natural_0')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('ochrum', 'ore')
        .stateSupplier(() => Block.getBlock('create:ochrum').defaultBlockState())
        .baseModelLocation('create:block/ochrum_natural_0')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('scoria', 'ore')
        .stateSupplier(() => Block.getBlock('create:scoria').defaultBlockState())
        .baseModelLocation('create:block/scoria')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
    event.create('scorchia', 'ore')
        .stateSupplier(() => Block.getBlock('create:scorchia').defaultBlockState())
        .baseModelLocation('create:block/scorchia')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
        .generateItem(true)
})

GTCEuStartupEvents.registry('gtceu:world_gen_layer', event => {
    event.create('otherside_layer')
        .targets('#kubejs:otherside_ore_replaceables')
        .dimensions('deeperdarker:otherside')
    event.create('aether_layer')
        .targets('#kubejs:aether_ore_replaceables')
        .dimensions('aether:the_aether')
})
*/