ServerEvents.recipes(event => {
    event.shaped(
        'gtceu:ammo_assembler',
        ['AWA', 'VSV', 'CLC'],
        {
            A: 'gtceu:hv_robot_arm',
            W: 'gtceu:hv_electric_pump',
            C: '#gtceu:circuits/hv',
            S: 'gtceu:clean_machine_casing',
            V: 'gtceu:hv_conveyor_module',
            L: 'gtceu:gold_double_cable'
        }
    ).id('gtceu:shaped/ammo_assembler')

//bullet
    event.recipes.gtceu.ammo_assembler('ammo_bullet_heavy_t1')
        .circuit(0)
        .itemInputs('1x gtceu:gold_foil', '2x additionalguns:casing_heavy')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 80))
        .itemOutputs('2x additionalguns:bullet_heavy')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_t2')
        .circuit(0)
        .itemInputs('1x gtceu:platinum_foil', '4x additionalguns:casing_heavy')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 160))
        .itemOutputs('4x additionalguns:bullet_heavy')
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_t3')
        .circuit(0)
        .itemInputs('1x gtceu:managold_foil', '6x additionalguns:casing_heavy')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 240))
        .itemOutputs('6x additionalguns:bullet_heavy')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_t4')
        .circuit(0)
        .itemInputs('1x gtceu:duranium_foil', '8x additionalguns:casing_heavy')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 320))
        .itemOutputs('8x additionalguns:bullet_heavy')
        .duration(20)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_bullet_long_t1')
        .circuit(0)
        .itemInputs('1x gtceu:gold_foil', '2x additionalguns:casing_long')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 80))
        .itemOutputs('2x additionalguns:bullet_long')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_t2')
        .circuit(0)
        .itemInputs('1x gtceu:platinum_foil', '4x additionalguns:casing_long')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 160))
        .itemOutputs('4x additionalguns:bullet_long')
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_t3')
        .circuit(0)
        .itemInputs('1x gtceu:managold_foil', '6x additionalguns:casing_long')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 240))
        .itemOutputs('6x additionalguns:bullet_long')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_t4')
        .circuit(0)
        .itemInputs('1x gtceu:duranium_foil', '8x additionalguns:casing_long')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 320))
        .itemOutputs('8x additionalguns:bullet_long')
        .duration(20)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_bullet_medium_t1')
        .circuit(0)
        .itemInputs('1x gtceu:gold_foil', '3x additionalguns:casing_medium')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 80))
        .itemOutputs('3x additionalguns:bullet_medium')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_t2')
        .circuit(0)
        .itemInputs('1x gtceu:platinum_foil', '6x additionalguns:casing_medium')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 160))
        .itemOutputs('6x additionalguns:bullet_medium')
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_t3')
        .circuit(0)
        .itemInputs('1x gtceu:managold_foil', '9x additionalguns:casing_medium')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 240))
        .itemOutputs('9x additionalguns:bullet_medium')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_t4')
        .circuit(0)
        .itemInputs('1x gtceu:duranium_foil', '12x additionalguns:casing_medium')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 320))
        .itemOutputs('12x additionalguns:bullet_medium')
        .duration(20)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_bullet_short_t1')
        .circuit(0)
        .itemInputs('1x gtceu:gold_foil', '4x additionalguns:casing_short')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 80))
        .itemOutputs('4x additionalguns:bullet_short')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_t2')
        .circuit(0)
        .itemInputs('1x gtceu:platinum_foil', '8x additionalguns:casing_short')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 160))
        .itemOutputs('8x additionalguns:bullet_short')
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_t3')
        .circuit(0)
        .itemInputs('1x gtceu:managold_foil', '12x additionalguns:casing_short')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 240))
        .itemOutputs('12x additionalguns:bullet_short')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_t4')
        .circuit(0)
        .itemInputs('1x gtceu:duranium_foil', '16x additionalguns:casing_short')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 320))
        .itemOutputs('16x additionalguns:bullet_short')
        .duration(20)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_bullet_small_t1')
        .circuit(0)
        .itemInputs('1x gtceu:gold_foil', '4x additionalguns:casing_small')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 80))
        .itemOutputs('4x additionalguns:bullet_small')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_t2')
        .circuit(0)
        .itemInputs('1x gtceu:platinum_foil', '8x additionalguns:casing_small')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 160))
        .itemOutputs('8x additionalguns:bullet_small')
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_t3')
        .circuit(0)
        .itemInputs('1x gtceu:managold_foil', '12x additionalguns:casing_small')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 240))
        .itemOutputs('12x additionalguns:bullet_small')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_t4')
        .circuit(0)
        .itemInputs('1x gtceu:duranium_foil', '16x additionalguns:casing_small')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 320))
        .itemOutputs('16x additionalguns:bullet_small')
        .duration(20)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_bullet_special_t1')
        .circuit(0)
        .itemInputs('1x gtceu:gold_foil', '2x additionalguns:casing_special')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 80))
        .itemOutputs('2x additionalguns:bullet_special')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_t2')
        .circuit(0)
        .itemInputs('1x gtceu:platinum_foil', '4x additionalguns:casing_special')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 160))
        .itemOutputs('4x additionalguns:bullet_special')
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_t3')
        .circuit(0)
        .itemInputs('1x gtceu:managold_foil', '6x additionalguns:casing_special')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 240))
        .itemOutputs('6x additionalguns:bullet_special')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_t4')
        .circuit(0)
        .itemInputs('1x gtceu:duranium_foil', '8x additionalguns:casing_special')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 320))
        .itemOutputs('8x additionalguns:bullet_special')
        .duration(20)
        .EUt(15360)

    //heavy
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_ss')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:stainless_steel', 72))
        .itemOutputs('2x additionalguns:casing_heavy')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_vs')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:vanadium_steel', 72))
        .itemOutputs('2x additionalguns:casing_heavy')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_ts')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 72))
        .itemOutputs('4x additionalguns:casing_heavy')
        .duration(80)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_hssg')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:hssg', 72))
        .itemOutputs('5x additionalguns:casing_heavy')
        .duration(70)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_hsss')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:hsss', 72))
        .itemOutputs('6x additionalguns:casing_heavy')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_nq')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:naquadah_alloy', 72))
        .itemOutputs('12x additionalguns:casing_heavy')
        .duration(30)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_yy')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:yinyang', 72))
        .itemOutputs('8x additionalguns:casing_heavy')
        .duration(40)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_heavy_ryy')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:reinforced_yinyang', 72))
        .itemOutputs('16x additionalguns:casing_heavy')
        .duration(10)
        .EUt(61440)

    //long
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_ss')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:stainless_steel', 72))
        .itemOutputs('2x additionalguns:casing_long')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_vs')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:vanadium_steel', 72))
        .itemOutputs('2x additionalguns:casing_long')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_ts')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 72))
        .itemOutputs('4x additionalguns:casing_long')
        .duration(80)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_hssg')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:hssg', 72))
        .itemOutputs('5x additionalguns:casing_long')
        .duration(70)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_hsss')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:hsss', 72))
        .itemOutputs('6x additionalguns:casing_long')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_nq')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:naquadah_alloy', 72))
        .itemOutputs('12x additionalguns:casing_long')
        .duration(30)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_yy')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:yinyang', 72))
        .itemOutputs('8x additionalguns:casing_long')
        .duration(40)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_long_ryy')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:reinforced_yinyang', 72))
        .itemOutputs('16x additionalguns:casing_long')
        .duration(10)
        .EUt(61440)

    //medium
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_ss')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:stainless_steel', 72))
        .itemOutputs('4x additionalguns:casing_medium')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_vs')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:vanadium_steel', 72))
        .itemOutputs('4x additionalguns:casing_medium')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_ts')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 72))
        .itemOutputs('8x additionalguns:casing_medium')
        .duration(80)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_hssg')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:hssg', 72))
        .itemOutputs('10x additionalguns:casing_medium')
        .duration(70)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_hsss')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:hsss', 72))
        .itemOutputs('12x additionalguns:casing_medium')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_nq')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:naquadah_alloy', 72))
        .itemOutputs('24x additionalguns:casing_medium')
        .duration(30)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_yy')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:yinyang', 72))
        .itemOutputs('16x additionalguns:casing_medium')
        .duration(40)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_medium_ryy')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:reinforced_yinyang', 72))
        .itemOutputs('32x additionalguns:casing_medium')
        .duration(10)
        .EUt(61440)

    //short
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_ss')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:stainless_steel', 72))
        .itemOutputs('8x additionalguns:casing_short')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_vs')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:vanadium_steel', 72))
        .itemOutputs('8x additionalguns:casing_short')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_ts')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 72))
        .itemOutputs('16x additionalguns:casing_short')
        .duration(80)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_hssg')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:hssg', 72))
        .itemOutputs('20x additionalguns:casing_short')
        .duration(70)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_hsss')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:hsss', 72))
        .itemOutputs('24x additionalguns:casing_short')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_nq')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:naquadah_alloy', 72))
        .itemOutputs('48x additionalguns:casing_short')
        .duration(30)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_yy')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:yinyang', 72))
        .itemOutputs('32x additionalguns:casing_short')
        .duration(40)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_short_ryy')
        .circuit(4)
        .inputFluids(Fluid.of('gtceu:reinforced_yinyang', 72))
        .itemOutputs('64x additionalguns:casing_short')
        .duration(10)
        .EUt(61440)

    //small
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_ss')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:stainless_steel', 72))
        .itemOutputs('8x additionalguns:casing_small')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_vs')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:vanadium_steel', 72))
        .itemOutputs('8x additionalguns:casing_small')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_ts')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 72))
        .itemOutputs('16x additionalguns:casing_small')
        .duration(80)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_hssg')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:hssg', 72))
        .itemOutputs('20x additionalguns:casing_small')
        .duration(70)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_hsss')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:hsss', 72))
        .itemOutputs('24x additionalguns:casing_small')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_nq')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:naquadah_alloy', 72))
        .itemOutputs('48x additionalguns:casing_small')
        .duration(30)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_yy')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:yinyang', 72))
        .itemOutputs('32x additionalguns:casing_small')
        .duration(40)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_small_ryy')
        .circuit(5)
        .inputFluids(Fluid.of('gtceu:reinforced_yinyang', 72))
        .itemOutputs('64x additionalguns:casing_small')
        .duration(10)
        .EUt(61440)

    //special
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_ss')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:stainless_steel', 72))
        .itemOutputs('2x additionalguns:casing_special')
        .duration(200)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_vs')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:vanadium_steel', 72))
        .itemOutputs('2x additionalguns:casing_special')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_ts')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 72))
        .itemOutputs('4x additionalguns:casing_special')
        .duration(80)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_hssg')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:hssg', 72))
        .itemOutputs('5x additionalguns:casing_special')
        .duration(70)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_hsss')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:hsss', 72))
        .itemOutputs('6x additionalguns:casing_special')
        .duration(60)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_nq')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:naquadah_alloy', 72))
        .itemOutputs('12x additionalguns:casing_special')
        .duration(30)
        .EUt(15360)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_yy')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:yinyang', 72))
        .itemOutputs('8x additionalguns:casing_special')
        .duration(40)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_casing_special_ryy')
        .circuit(6)
        .inputFluids(Fluid.of('gtceu:reinforced_yinyang', 72))
        .itemOutputs('16x additionalguns:casing_special')
        .duration(10)
        .EUt(61440)

    //shell
    event.recipes.gtceu.ammo_assembler('ammo_shell_t1')
        .circuit(7)
        .itemInputs('1x gtceu:gold_foil', '16x gtceu:lead_nugget')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 50))
        .itemOutputs('1x cgm:shell')
        .duration(300)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_shell_t2')
        .circuit(7)
        .itemInputs('1x gtceu:platinum_foil', '24x gtceu:tungsten_nugget')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 100))
        .itemOutputs('2x cgm:shell')
        .duration(150)
        .EUt(960)
    event.recipes.gtceu.ammo_assembler('ammo_shell_t3')
        .circuit(7)
        .itemInputs('1x gtceu:duranium_foil', '24x gtceu:osmium_nugget')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 300))
        .itemOutputs('6x cgm:shell')
        .duration(70)
        .EUt(7680)
    event.recipes.gtceu.ammo_assembler('ammo_shell_t3_alt')
        .circuit(7)
        .itemInputs('1x gtceu:managold_foil', '32x gtceu:osmium_nugget')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 200))
        .itemOutputs('4x cgm:shell')
        .duration(100)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_shell_t4')
        .circuit(7)
        .itemInputs('1x gtceu:duranium_foil', '24x gtceu:naquadah_alloy_nugget')
        .inputFluids(Fluid.of('gtceu:glyceryl_trinitrate', 400))
        .itemOutputs('8x cgm:shell')
        .duration(30)
        .EUt(15360)

    //misc
    event.recipes.gtceu.ammo_assembler('ammo_grenade_t1')
        .circuit(8)
        .itemInputs('1x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:stainless_steel', 144))
        .itemOutputs('2x cgm:grenade')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_grenade_t2')
        .circuit(8)
        .itemInputs('1x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 144))
        .itemOutputs('4x cgm:grenade')
        .duration(50)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_stun_grenade_t1')
        .circuit(9)
        .itemInputs('1x minecraft:gunpowder', '4x minecraft:glowstone_dust')
        .inputFluids(Fluid.of('gtceu:stainless_steel', 144))
        .itemOutputs('2x cgm:stun_grenade')
        .duration(240)
        .EUt(240)
    event.recipes.gtceu.ammo_assembler('ammo_stun_grenade_t2')
        .circuit(9)
        .itemInputs('1x minecraft:gunpowder', '4x minecraft:glowstone_dust')
        .inputFluids(Fluid.of('gtceu:tungsten_steel', 144))
        .itemOutputs('4x cgm:stun_grenade')
        .duration(50)
        .EUt(3840)
    event.recipes.gtceu.ammo_assembler('ammo_missile_t1')
        .circuit(10)
        .itemInputs('1x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:stainless_steel', 288), Fluid.of('gtceu:rocket_fuel', 1000))
        .itemOutputs('1x cgm:missile')
        .duration(500)
        .EUt(480)
    event.recipes.gtceu.ammo_assembler('ammo_missile_t2')
        .circuit(10)
        .itemInputs('1x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:niobium_titanium', 144), Fluid.of('gtceu:rocket_fuel', 500))
        .itemOutputs('1x cgm:missile')
        .duration(240)
        .EUt(7680)

})