ServerEvents.recipes(event => {
    event.shaped(
        'gtceu:genetic_extractor',
        ['MGP', 'CSC', 'LCL'],
        {
            M: 'gtceu:luv_electric_motor',
            P: 'gtceu:luv_electric_pump',
            G: 'gtceu:luv_sensor',
            C: '#gtceu:circuits/luv',
            S: 'gtceu:clean_machine_casing',
            L: 'gtceu:niobium_titanium_single_cable'
        }
    ).id('gtceu:shaped/genetic_extractor')

    event.recipes.gtceu.extruder('ep_t1')
        .itemInputs('1x gtceu:small_polytetrafluoroethylene_dust')
        .notConsumable("gtceu:cell_extruder_mold")
        .itemOutputs('4x kubejs:ep_empty')
        .duration(116)
        .EUt(480)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.extruder('ep_t2')
        .itemInputs('1x gtceu:small_polybenzimidazole_dust')
        .notConsumable("gtceu:cell_extruder_mold")
        .itemOutputs('16x kubejs:ep_empty')
        .duration(116)
        .EUt(480)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)

    event.recipes.gtceu.genetic_extractor('gene_chicken_a')
        .itemInputs('1x minecraft:chicken', '8x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 160), Fluid.of('gtceu:chloroform', 320))
        .itemOutputs('8x kubejs:gene_of_chicken')
        .duration(264)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_chicken_b')
        .itemInputs('1x minecraft:egg', '3x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 60), Fluid.of('gtceu:chloroform', 120))
        .itemOutputs('3x kubejs:gene_of_chicken')
        .duration(104)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_chicken_c')
        .circuit(1)
        .itemInputs('1x minecraft:feather', '2x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 40), Fluid.of('gtceu:chloroform', 80))
        .itemOutputs('2x kubejs:gene_of_chicken')
        .duration(72)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_cow_a')
        .itemInputs('1x minecraft:beef', '12x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 240), Fluid.of('gtceu:chloroform', 480))
        .itemOutputs('12x kubejs:gene_of_cow')
        .duration(392)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_cow_b')
        .circuit(1)
        .itemInputs('1x minecraft:leather', '4x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 80), Fluid.of('gtceu:chloroform', 160))
        .itemOutputs('4x kubejs:gene_of_cow')
        .duration(136)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_sheep_a')
        .itemInputs('1x minecraft:mutton', '10x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 200), Fluid.of('gtceu:chloroform', 400))
        .itemOutputs('10x kubejs:gene_of_sheep')
        .duration(328)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_sheep_b')
        .circuit(1)
        .itemInputs('1x #minecraft:wool', '3x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 60), Fluid.of('gtceu:chloroform', 120))
        .itemOutputs('3x kubejs:gene_of_sheep')
        .duration(104)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_pig_a')
        .itemInputs('1x minecraft:porkchop', '10x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 200), Fluid.of('gtceu:chloroform', 400))
        .itemOutputs('10x kubejs:gene_of_pig')
        .duration(328)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
    event.recipes.gtceu.genetic_extractor('gene_pig_b')
        .circuit(1)
        .itemInputs('1x farmersdelight:ham', '12x kubejs:ep_empty')
        .inputFluids(Fluid.of('gtceu:ethanol', 240), Fluid.of('gtceu:chloroform', 480))
        .itemOutputs('10x kubejs:gene_of_pig')
        .duration(392)
        .EUt(30720)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)
})